server:
  port: 9180

memento:
  kms:
    key-id: "21fc1e9e-a4c9-4bb6-a4c9-7b5a5cff8e64"
  kafka:
    bootstrap-addresses: "3.34.15.173:9092,3.39.13.67:9092,3.39.163.32:9092"
    username: "reason"
    password: "admin-reason"